services:
    app.exception_listener:
        class: EMC\FileinputBundle\EventListener\ExceptionListener
        calls:
            - [setFilterConfiguration, [@liip_imagine.filter.configuration]]
            - [setEm, [@doctrine.orm.entity_manager]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }