services:
    emc.fileinput.form.type:
        class: EMC\FileinputBundle\Form\Type\FileinputType
        tags:
            - { name: form.type, alias: fileinput }
        calls:
            - [ setUploadableManager, [@emc.fileinput.uploadable.manager]]
            - [ setFileClass, [%emc_fileinput.file_class%]]

    emc.fileinput.uploadable.manager:
        class: EMC\FileinputBundle\Gedmo\Uploadable\UploadableManager
        arguments: [@doctrine.orm.entity_manager, @emc.fileinput.uploadable.registry]
            
    emc.fileinput.uploadable.registry:
        class: EMC\FileinputBundle\Gedmo\Uploadable\UploadableRegistry
        arguments: [[]]
        calls:
            - [setContainer, [@service_container]]
    
    emc.fileinput.uploadable.listener.default:
        class: EMC\FileinputBundle\Gedmo\Uploadable\DefaultUploadableListener
        arguments: [@stof_doctrine_extensions.uploadable.mime_type_guesser]
        calls:
            - [setAnnotationReader, [@annotation_reader]]
            - [setDefaultFileInfoClass, [%stof_doctrine_extensions.uploadable.default_file_info.class%]]
        tags:
            - { name: doctrine.event_subscriber }
        
    emc.fileinput.uploadable.manager.default:
        class: %stof_doctrine_extensions.uploadable.manager.class%
        arguments: [@emc.fileinput.uploadable.listener.default, %stof_doctrine_extensions.uploadable.default_file_info.class%]
        tags:
            - { name: emc.fileinput.uploadable, alias: default }
    
    emc.fileinput.uploadable.listener.vimeo:
        class: EMC\FileinputBundle\Gedmo\Uploadable\VimeoUploadableListener
        arguments: [@stof_doctrine_extensions.uploadable.mime_type_guesser]
        calls:
            - [setAnnotationReader, [@annotation_reader]]
            - [setDefaultFileInfoClass, [%stof_doctrine_extensions.uploadable.default_file_info.class%]]
            - [setDriver, [@emc.vimeo]]
        tags:
            - { name: doctrine.event_subscriber }
        
    emc.fileinput.uploadable.manager.vimeo:
        class: %stof_doctrine_extensions.uploadable.manager.class%
        arguments: [@emc.fileinput.uploadable.listener.vimeo, %stof_doctrine_extensions.uploadable.default_file_info.class%]
        tags:
            - { name: emc.fileinput.uploadable, alias: vimeo }
    
    emc.vimeo:
        class: EMC\FileinputBundle\Driver\VimeoDriver
        arguments:
            - %emc_fileinput.providers.vimeo.client_id%
            - %emc_fileinput.providers.vimeo.client_secret%
            - %emc_fileinput.providers.vimeo.access_token%
            - %emc_fileinput.providers.vimeo.settings%
            - %emc_fileinput.providers.vimeo.whitelist%