parameters:
    form.type.fileinput.class: EMC\FileinputBundle\Form\Type\FileinputType
services:
    form.type.fileinput:
        class: %form.type.fileinput.class%
        tags:
            - { name: form.type, alias: fileinput }
        calls:
            - [ setUploadableManager, [@stof_doctrine_extensions.uploadable.manager]]
            - [ setFileClass, [%emc_fileinput.file_class%]]
